Traceback (most recent call last):
  File "main.py", line 139, in <module>
    out = model(x_data) 
  File "/zhome/88/7/117159/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/88/7/117159/Desktop/BCI_MI_Classification/models.py", line 174, in forward
    X_data, _ = self.lstm(X_data)
  File "/zhome/88/7/117159/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/88/7/117159/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 582, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 104.00 MiB (GPU 0; 31.75 GiB total capacity; 6.23 GiB already allocated; 26.50 MiB free; 6.44 GiB reserved in total by PyTorch)
