Traceback (most recent call last):
  File "main.py", line 79, in <module>
    loss_collect, val_loss_collect, model = train_model(model, optimizer, criterion, NUM_EPOCHS, train_dataloader, test_dataloader, device, scheduler = None)	
  File "/zhome/88/7/117159/Desktop/BCI_MI_Classification/train_function.py", line 30, in train_model
    loss.backward()
  File "/zhome/88/7/117159/.local/lib/python3.6/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/zhome/88/7/117159/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 104.00 MiB (GPU 0; 31.75 GiB total capacity; 3.32 GiB already allocated; 51.50 MiB free; 3.40 GiB reserved in total by PyTorch)
