Traceback (most recent call last):
  File "main.py", line 65, in <module>
    loss_collect, val_loss_collect, model = train_model(model, optimizer, criterion, NUM_EPOCHS, train_dataloader, test_dataloader, device, scheduler = None)	
  File "/zhome/08/3/117881/BCI_Project/BCI_MI_Classification/train_function.py", line 30, in train_model
    loss.backward()
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 1.38 GiB (GPU 0; 31.75 GiB total capacity; 8.77 GiB already allocated; 88.00 MiB free; 8.95 GiB reserved in total by PyTorch)
